# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet', models.CharField(default='Null', max_length=32)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
